version: '3.9'

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: climasense
    ports:
      - '5432:5432'

  api:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/climasense
      PORT: 3000
      MQTT_BROKER: mqtt://broker.hivemq.com:1883
      MQTT_TOPIC: climasense/ghana/northern/readings
    ports:
      - '3000:3000'
